!
ip prefix-list ONLY-LOOPBACK permit 172.16.255.255/32
!
route-map RM-OUT permit 10
 match ip address prefix-list ONLY-LOOPBACK
exit
!
route-map RM-IN permit 10
exit
!
router bgp 65501
 bgp router-id 172.16.255.255
 no bgp default ipv4-unicast
 !
 ! Define neighbors
 neighbor 172.16.255.0 remote-as 64255
 neighbor 172.16.255.2 remote-as 64255
 !
 address-family ipv4 unicast
  ! Advertise the loopback IP into BGP
  network 172.16.255.255/32
  
  ! Apply policies to Neighbor 172.16.255.0
  neighbor 172.16.255.0 activate
  neighbor 172.16.255.0 route-map RM-IN in
  neighbor 172.16.255.0 route-map RM-OUT out
  
  ! Apply policies to Neighbor 172.16.255.2
  neighbor 172.16.255.2 activate
  neighbor 172.16.255.2 route-map RM-IN in
  neighbor 172.16.255.2 route-map RM-OUT out
 exit-address-family
exit
!
end
