!
frr defaults traditional
hostname storage-svr-01
no ipv6 forwarding
!
ip prefix-list EXPORT-ONLY-LOOPBACK seq 5 permit 192.168.0.0/16 ge 32 le 32
ip prefix-list ACCEPT-STORAGE seq 10 permit 192.168.0.0/16 ge 16 le 32
!
router bgp 65256
 bgp router-id 192.168.255.2
 bgp bestpath as-path multipath-relax
 neighbor LEAF peer-group
 neighbor eth1.1 interface peer-group LEAF
 neighbor eth1.1 remote-as 65255
 neighbor eth1.1 description fe-leaf03
 neighbor eth2.1 interface peer-group LEAF
 neighbor eth2.1 remote-as 65255
 neighbor eth2.1 description fe-leaf04
 !
 address-family ipv4 unicast
  network 192.168.255.2/32
  neighbor LEAF soft-reconfiguration inbound
  neighbor LEAF route-map IMPORT-STORAGE in
  neighbor LEAF route-map EXPORT-ONLY-LOOPBACK out
 exit-address-family
exit
!
route-map EXPORT-ONLY-LOOPBACK permit 10
 match ip address prefix-list EXPORT-ONLY-LOOPBACK
exit
!
route-map IMPORT-STORAGE permit 10
 match ip address prefix-list ACCEPT-STORAGE
exit
!
end