apiVersion: config.eda.nokia.com/v1alpha1
kind: Configlet
metadata:
  name: max-path
  namespace: ai-fabric-be
spec:
  configs:
  - config: |
      {
        "allow-multiple-as": true,
        "ebgp": {
          "maximum-paths": 8
        },
        "ibgp": {
          "maximum-paths": 8
        }
      }
    operation: Create
    path: .network-instance{.name=="default"}.protocols.bgp.afi-safi{.afi-safi-name=="ipv4-unicast"}.multipath
  endpoints:
  - 2tier-beleaf-01
  - 2tier-beleaf-02
  operatingSystem: srl
  priority: 100
  version: 25.7.2
