apiVersion: aifabrics.eda.nokia.com/v1alpha1
kind: Backend
metadata:
  name: ai-backend-fabric
  namespace: ai-fabric-be
spec:
  asnPool: asn-pool
  gpuIsolationGroups:
    - interfaceSelector:
        - eda.nokia.com/tenant=gpucluster1
      name: islgrp1
    - interfaceSelector:
        - eda.nokia.com/tenant=gpucluster2
      name: islgrp2
    - interfaceSelector:
        - eda.nokia.com/tenant=gpucluster3
      name: islgrp3
    - interfaceSelector:
        - eda.nokia.com/tenant=gpucluster4
      name: islgrp4
    - interfaceSelector:
        - eda.nokia.com/tenant=gpucluster5
      name: islgrp5
    - interfaceSelector:
        - eda.nokia.com/tenant=gpucluster6
      name: islgrp6
    - interfaceSelector:
        - eda.nokia.com/tenant=gpucluster7
      name: islgrp7
    - interfaceSelector:
        - eda.nokia.com/tenant=gpucluster8
      name: islgrp8
  rocev2QoS:
    ecnMaxDropProbabilityPercent: 100
    ecnSlopeMaxThresholdPercent: 80
    ecnSlopeMinThresholdPercent: 5
    pfcDeadlockDetectionTimer: 750
    pfcDeadlockRecoveryTimer: 750
    queueMaximumBurstSize: 52110640
  stripeConnector:
    asnPool: asn-pool-spine
    linkSelector:
      - eda.nokia.com/role=interSwitchBE
    name: stripeconn01
    nodeSelector:
      - eda.nokia.com/stripeconn-id=stripeconn01
    systemPoolIPV4: system0-spine
  stripes:
    - asnPool: asn-pool-leaf
      gpuVlan: 1
      name: stripe01
      nodeSelector:
        - eda.nokia.com/stripe-id=stripe1
      stripeID: 1
      systemPoolIPV4: system0-leaf
